//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comment.java
//  @ Date : 2016/4/23
//  @ Author : 
//
//
package adriftbook.entity;
import java.util.Calendar;
public class Comment
{

    private String content;
    private Calendar reviewDate;
    public Comment(String content, Calendar reviewDate)
    {
        this.content = content;
        this.reviewDate = reviewDate;
    }
    public String getContent()
    {
        return content;
    }
    public void setContent(String content)
    {
        this.content = content;
    }
    public Calendar getReviewDate()
    {
        return reviewDate;
    }
    public void setReviewDate(Calendar reviewDate)
    {
        this.reviewDate = reviewDate;
    }
}
