//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comment.java
//  @ Date : 2016/4/23
//  @ Author : 
//
//
package adriftbook.entity;
import java.util.Calendar;
public class Comment
{

    private int commentId;
    private Post commentPost;
    User commentUser;
    private String commentContent;
    private Calendar reviewDate;
    public Comment(Post commentPost, User commentUser, String commentContent)
    {
        this.commentPost = commentPost;
        this.commentUser = commentUser;
        this.commentContent = commentContent;
        reviewDate = Calendar.getInstance();
    }
    public int getCommentId()
    {
        return commentId;
    }
    @Override public String toString()
    {
        return "Comment{" +
                "commentId=" + commentId +
                ", commentPost=" + commentPost +
                ", commentUser=" + commentUser +
                ", commentContent='" + commentContent + '\'' +
                ", reviewDate=" + reviewDate +
                '}';
    }
    public void setCommentId(int commentId)
    {
        this.commentId = commentId;
    }
    public String getCommentContent()
    {
        return commentContent;
    }
    public void setCommentContent(String commentContent)
    {
        this.commentContent = commentContent;
    }
    public Calendar getReviewDate()
    {
        return reviewDate;
    }
    public void setReviewDate(Calendar reviewDate)
    {
        this.reviewDate = reviewDate;
    }
}
