//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Content.java
//  @ Date : 2016/4/23
//  @ Author : 
//
//


package adriftbook.entity;

public class Content {
	private String textCcontent;
	private String bookImageUrl;
	private Content(String textCcontent)
	{
		this.textCcontent=textCcontent;
	}
	private Content(String textCcontent,String bookImageUrl)
	{
		this(textCcontent);
		this.bookImageUrl=bookImageUrl;
	}
	public String getTextCcontent()
	{
		return textCcontent;
	}
	public void setTextCcontent(String textCcontent)
	{
		this.textCcontent = textCcontent;
	}
	public String getBookImageUrl()
	{
		return bookImageUrl;
	}
	public void setBookImageUrl(String bookImageUrl)
	{
		this.bookImageUrl = bookImageUrl;
	}
}
