//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Post.java
//  @ Date : 2016/4/23
//  @ Author : 
//
//
package adriftbook.entity;
import java.util.Calendar;
public class Post
{

    User postUser;
    private int postId;
    private String postTitle;
    private PostContent postContent;
    private Calendar postDate;
    private int postType;  //1求漂区，2放漂区，3电子书籍
    private int readCount;
    public Post(User postUser, String postTitle, String content)
    {
        this.postUser = postUser;
        this.postTitle = postTitle;
        postContent = new PostContent(content);
    }
    public Calendar getPostDate()
    {
        return postDate;
    }
    public void setPostDate(Calendar postDate)
    {
        this.postDate = postDate;
    }
    public int getPostType()
    {
        return postType;
    }
    public void setPostType(int postType)
    {
        this.postType = postType;
    }
    public int getReadCount()
    {
        return readCount;
    }
    public void setReadCount(int readCount)
    {
        this.readCount = readCount;
    }
}

