//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 2016/4/23
//  @ Author : 
//
//
package adriftbook.entity;
import java.util.Calendar;
public class User
{

    private String name;
    private int id;
    private String password;
    private Calendar registerDate;
    private int level;
    public String getName()
    {
        return name;
    }
    public void setName(String name)
    {
        this.name = name;
    }
    public String getPassword()
    {
        return password;
    }
    public void setPassword(String password)
    {
        this.password = password;
    }
    public Calendar getRegisterDate()
    {
        return registerDate;
    }
    public void setRegisterDate(Calendar registerDate)
    {
        this.registerDate = registerDate;
    }
    public int getLevel()
    {
        return level;
    }
    public void setLevel(int level)
    {
        this.level = level;
    }
}
